import LocalizedStrings from "react-native-localization";
import { GRAPH_URL_DARK, GRAPH_URL_LIGHT } from "./src/EndPoints";
import { Colors, Images } from "./src/theme";

export let ThemeManager = new LocalizedStrings({
  //light theme
  theme1: {
    colors: {
      // tabBackground: '#F5F5F5',
      // tabActiveBackgroundColor: '#F5F5F5',
      // DashboardBG: '#F5F5F5',
      // dashboardSearchBarBg: '#FFFFFF',
      anouncementtextColour: "#707988",
      // dashboardSubViewBg: '#FFFFFF',
      // dashboardItemTextColor: '#707988',
      // textColor: '#000000',
      // tabBg: '#F5F5F5',
      // textGreenColor: '#00C35D',
      // textRedColor: '#F6465D',
      // screenBackgroundColor: '#F5F5F5',
      // tabBottomBorder: '#E3BA00',
      // selectedTextColor: '#E3BA00',
      // currencyTabColor: '#F5F5F5',
      // whiteScreen: '#FFFFFF',
      // inactiveTextColor: '#707988',
      // borderColor: '#AFB3BE',
      // btnGreenColor: '#00C35D',
      // inputColor: '#FFFFFF',
      // btnColor: '#F5F5F5',
      // btnColor2: '#FFFFFF',
      // placeholderTextColor: '#4C5562',
      // convertBox: '#FFFFFF',
      // modalBox: '#F5F5F5',
      // anouncementtextColour:'#AFB3BE'
      textColor1: "#000000",
      themeColor: "light",
      confirmBtn: "#707988",
      cryptoAmountTextColor: "#000000",
      placeholderColorInsideForLight: "rgba(255,255,255,0.30)",
      SwapInput: "#F3F3F3",//"#F4F4F4",
      perCentTabSpot: "#ffff",
      tabBackground: "#F4F4F4",
      bgDarkwhite: "#fff",
      // inputColor2: 'black',
      Shadow: "black",
      tabActiveBackgroundColor: "#f4f4f4",
      DashboardBG: "#ffff",
      dashboardSearchBarBg: "#F7F7F8",
      widrawInput: "#ffff",
      SubViewBg: "#fff",
      // anouncementtextColour: '#707988',
      dashboardSubViewBg: "#ffffff",
      depositWithdrwatHeader: "#ffffff",
      dashboardItemTextColor: "#707988",
      textColor: "#000000",
      // textColor1: '#000000',
      SpotCard: "#222631",
      textBWw: "#fff",
      textBW: "#333333",
      textBW2: "black",
      textBW3: "#333333",

      cryptoSerach: "#707988",
      headTxt: "black",
      taninActive: "#707988",
      tabtext: "#0000",
      walletDPbtn: "#61CAE6",
      BackgroundDarkView: "#ffffff",
      tabBg: "#f4f4f4",
      textGreenColor: "#00C35D",
      textRedColor: "#F6465D",
      screenBackgroundColor: "#F5F5F5",
      tabBottomBorder: "#61CAE6",
      Depositbtn: "#6DD59D",
      filter: "#61CAE6",
      selectedTextColor: "#61CAE6",
      currencyTabColor: "#F5F5F5",
      whiteScreen: "#FFFFFF",
      inactiveTextColor: "#A1A1A1",
      walletCheckColor: "#ffff",
      searchCountry: "#F7F7F8",
      Arrow: "#707988",
      borderColor: "#A1A0A0",//"#AFB3BE",
      btnGreenColor: "#00C35D",
      Purewhite: "#ffff",
      walletInfo: "#61CAE6",
      inputColor: "#FFFFFF",
      btnColor: "#F5F5F5",
      CoinColor: "#707988",
      btnColor2: "#FFFFFF",
      placeholderTextColor: "#4C5562",
      convertBox: "#FFFFFF",
      modalBox: "#ffff",
      walletDPbtnborder: "#fff",
      crypto_input: "#f3f5f9",
      rewHisbg: "#EFEFEF",
      greyWhiteColor: "#6b6b6b",
      tickerBg: "#e2e4e9",
      refBGColor: "#f2f2f2",
      lightGreen: "#2c5454",
      greenColor: "#325959",
      blue: "#0000EE",
      textColor2: "#11151D",
      textColor3: "#A1A1A1",
      textColor4: "#000000",
      headerText: "#A1A1A1",
      headerActiveText: "#000000",
      headerInActiveText: "#000000",
      inputBackground: "#F4F4F4",
      inputBackgroundChange: "#F3F3F3",
      textColor5: "#11151D",
      withdrawText: "#6DD59D",
      btnColor3: "#11151D",
      locationText: "#A1A1A1",
      modalBg: "#FFFFFF",

      modalTitle: "#11151D",
      modalTitle1: "#A1A1A1",

      bgNewColor: "#fff",
      imageLogoTintColor: "#000000",
      black_white: "#000000",
      lightText83: "#838383",
    },

    ImageIcons: {
      // dashboardUser: Images.dashboardUser,
      // dashboard_search_icon: Images.dashboard_search_icon,
      icon_scan: Images.icon_scanLight,
      // icon_Notification: Images.icon_notificationLight,
      // market_search_icon: Images.icon_search_light,
      icon_market_filter_right: Images.icon_market_filter_right_light,
      // icon_back_arrow: Images.icon_back_arrow_light,
      // icon_swap: Images.icon_swap_light,
      icon_trade_right: Images.icon_trade_right_light,
      icon_star: Images.icon_star_light,
      icon_dropdown: Images.icon_dropdown_dark,
      // icon_switch: Images.icon_switch_light,
      icon_note: Images.icon_note_light,
      icon_open_order: Images.icon_open_order_light,
      icon_spot_right: Images.icon_spot_right_light,
      icon_no_open_order: Images.icon_no_open_order_light,
      // icon_eye: Images.icon_eye_light,
      icon_note_time: Images.icon_note_time_light,
      icon_info: Images.icon_info_light,
      icon_select: Images.icon_select_light,
      icon_profile: Images.icon_profile_light,
      icon_del_back: Images.icon_del_back_light,
      icon_forward: Images.icon_forward_light,
      // location_header_Icon: Images.earth,
      // icon_back: Images.icon_back,
      // icon_logo: Images.Logo,
      // refBanner: Images.ref_banner_light,
      icon_buy_sell: Images.icon_buy_sell,
      icon_checked: Images.icon_checked,
      //icon new
      icon_home_active: Images.iconHomeActiveLight,
      icon_home_inactive: Images.iconHomeInactiveLight,
      icon_market_active: Images.iconMarketActiveLight,
      icon_market_inactive: Images.iconMarketInactiveLight,
      icon_trade_active: Images.iconTradesActiveLight,
      icon_trade_inactive: Images.iconTradeInActiveLight,
      icon_wallet_active: Images.iconWalletActiveLight,
      icon_wallet_inactive: Images.iconWalletInactiveLight,
      icon_card_active: Images.iconCardActiveLight,
      icon_card_inactive: Images.iconCardsInactiveLight,
      icon_profile_k: Images.icon_profile_light_k,
      icon_notification_k: Images.icon_notification_light_k,

      icon_deposit: Images.iconDepositLight,
      icon_withdraw: Images.iconWithdrawLight,
      icon_spot: Images.iconSpotLight,
      icon_swap_k: Images.iconSwapLight,
      icon_earth: Images.icon_earth_light,
      icon_open_eye: Images.icon_open_eye_light,
      icon_select_k: Images.icon_select_light_k,
      icon_cross: Images.cross_light,
      noOpenOrder: Images.noOpenOrderLight,
      icon_add: Images.icon_add_light,
      icon_back: Images.icon_back_light,
      mode: Images.mode_light,
      icon_forward_arrow: Images.icon_forward_arrow_light,
      icon_Profile_Settings: Images.icon_Profile_Settings_light,
      icon_Profile_Kyc: Images.icon_Profile_Kyc_light,
      icon_profile_Share: Images.icon_profile_Share_light,
      Icon_Profile_Copy: Images.Icon_Profile_Copy_light,
      icon_facebook: Images.icon_facebook_light,
      icon_telegram: Images.icon_telegram_light,
      icon_twitter: Images.icon_twitter_light,
      icon_update: Images.icon_update_dark,
      icon_phone: Images.icon_phone_light,
      Logo_MAIN: Images.Logo_MAIN_Light,
      iconCardsInactive: Images.iconCardsInactiveLight,
      iconCardActive: Images.iconCardActiveLight,
      icon_User_CreateAccount: Images.icon_User_CreateAccount_light,
      icon_indentity_CreateAccount: Images.icon_indentity_CreateAccount_light,

      iconDeleteUser: Images.iconDeleteUserLight,
      icon_ph: Images.icon_ph_light,
      icon_caution: Images.icon_caution_light,
      icon_down: Images.icon_down_light,
      icon_up: Images.icon_up_light,
      freeze_card: Images.freeze_card_light,
      view_pin: Images.view_pin_light,
      icon_upload_doc: Images.icon_upload_doc_light,
      icon_edit: Images.icon_edit_light,
      icon_replace_card: Images.icon_replace_card_light,
      qr_scanner: Images.qr_scanner_light,
      // icon_spot_right: Images.icon_spot_right_light,


      // icon_search_text: Images.search_text_icon,//icon_search_text_light,
      icon_search_text: Images.icon_search_text_light,

      // icon_swap_c: Images.swap_location,//Images.icon_swap_light_k,
      icon_swap_c: Images.icon_swap_light_k,

      // icon_hide_eye: Images.hidePassword,//icon_hide_eye_light,
      icon_hide_eye: Images.icon_hide_eye_light,

      // icon_close_main: Images.closeLogin,//Images.icon_close_light,
      icon_close_main: Images.icon_close_light,

      bgImage: "",
      earth_icon: Images.icon_earth_light,//earth_icon,
    },
  },
  //dark theme
  theme2: {
    colors: {
      textColor1: "#FFFFFF",
      blue: "#FFFFFF",
      SwapInput: "#1A1A1A",//"#1E2635",
      bgDarkwhite: "#000000",//"#171c28",
      walletDPbtnborder: "#6DD59D",
      inputColor2: "black",
      tabActiveBackgroundColor: "#202939",
      tabBackground: "#1E2635",
      DashboardBG: "#1A1A1A", //"#171C28", Change Because need backgrond color on change phone no
      SpotCard: "transparent",
      searchCountry: "#F7F7F8",
      perCentTabSpot: "#ffff",
      cryptoSerach: "#707988",
      dashboardSearchBarBg: "#2D2D2D",
      // anouncementtextColour: '#AFB3BE',
      anouncementtextColour: "#AFB3BE",
      dashboardSubViewBg: "#171c28",
      SubViewBg: "#2D2D2D",
      depositWithdrwatHeader: "#171c28",
      BackgroundDarkView: "#171c28",
      dashboardItemTextColor: "#AFB3BE",
      textBW: "#ffff",
      Shadow: "#6DD59D",
      textBW2: "black",
      textBWw: "black",
      textBW3: "#707988",
      widrawInput: "#2D2D2D",
      textColor: "#ffffff",
      // textColor1: '#ffff',

      headTxt: "#ffff",
      Arrow: "#AFB3BE",
      taninActive: "#707988",
      tabtext: "#ffff",
      tabBg: "#202939",
      Purewhite: "#ffff",
      screenBackgroundColor: "#171E26",
      inactiveTextColor: "#B9BBBF",
      textGreenColor: "#00C35D",
      textRedColor: "#F6465D",
      walletDPbtn: "#6DD59D",
      tabBottomBorder: "#6DD59D",
      walletInfo: "#6DD59D",
      Depositbtn: "#6DD59D",
      filter: "#6DD59D",
      selectedTextColor: "#6DD59D",
      walletCheckColor: "#6DD59D",
      currencyTabColor: "#434C5A",
      whiteScreen: "#171E26",
      borderColor: "#353535",//"#AFB3BE",
      btnGreenColor: "#00C35D",
      inputColor: "#29313C",
      btnColor: "#333B46",
      CoinColor: "#707988",
      btnColor2: "#333B46",
      placeholderTextColor: "#4C5562",
      convertBox: "#434C5B",
      modalBox: "#171c28",
      //
      // tabActiveBackgroundColor: '#434C5A',
      // tabBackground: '#29313C',
      // DashboardBG: '#171E26',
      // dashboardSearchBarBg: '#232C35',
      // anouncementtextColour: '#AFB3BE',
      // dashboardSubViewBg: '#1F2630',
      // dashboardItemTextColor: '#AFB3BE',
      // textColor: '#FFFFFF',
      // tabBg: '#434C5A',
      // screenBackgroundColor: '#171E26',
      // inactiveTextColor: '#707988',
      // textGreenColor: '#00C35D',
      // textRedColor: '#F6465D',
      // tabBottomBorder: '#E3BA00',
      // selectedTextColor: '#E3BA00',
      // currencyTabColor: '#434C5A',
      // whiteScreen: '#171E26',
      // borderColor: '#AFB3BE',
      // btnGreenColor: '#00C35D',
      // inputColor: '#29313C',
      // btnColor: '#333B46',
      // btnColor2: '#333B46',
      // placeholderTextColor: '#4C5562',
      // convertBox: '#434C5B',
      confirmBtn: "#434C5B",
      // modalBox: '#1F2630',
      themeColor: "dark",
      cryptoAmountTextColor: "#ffffff",
      placeholderColorInsideForLight: "rgba(0,0,0,0.30)",
      crypto_input: "#29313C",
      rewHisbg: "#313E4F",
      greyWhiteColor: "rgba(255,255,255,0.8)",
      refBGColor: "#252C37",
      tickerBg: "#303C4D",
      lightGreen: "#ffffff",
      greenColor: "#ffffff",
      textColor2: "#ffffff",
      textColor3: "#C4C4C4",
      textColor4: "#B9BBBF",
      headerText: "#B9BBBF",
      textColor5: "#B9BBBF",
      headerActiveText: "#FFFFFF",
      headerInActiveText: "#B9BBBF",
      inputBackground: "#1E2635",
      inputBackgroundChange: "#000000",
      withdrawText: "#FFFFFF",
      btnColor3: "#6DD59D",
      locationText: "#FFFFFF",
      modalBg: "#202939",
      modalTitle: "#DEDFE3",
      modalTitle1: "#DEDFE3",

      bgNewColor: "transparent",
      imageLogoTintColor: "",
      black_white: "#FFFFFF",
      lightText83: "#838383",

    },
    ImageIcons: {
      // dashboardUser: Images.dashboardUser,
      // dashboard_search_icon: Images.dashboard_search_icon,
      icon_scan: Images.Icon_Scan,
      // icon_Notification: Images.icon_Notification,
      // market_search_icon: Images.icon_search_dark,
      icon_market_filter_right: Images.icon_market_filter_right_dark,
      // icon_back_arrow: Images.icon_back_arrow_dark,
      // icon_swap: Images.icon_swap_dark,
      icon_trade_right: Images.icon_trade_right_dark,
      // icon_star: Images.icon_star_dark,
      icon_dropdown: Images.icon_dropdown_dark,
      // icon_switch: Images.icon_switch_dark,
      icon_note: Images.icon_note_dark,
      icon_open_order: Images.icon_open_order_dark,
      // icon_spot_right: Images.icon_spot_right_light,
      icon_no_open_order: Images.icon_no_open_order_dark,
      icon_eye_light: Images.icon_eye_dark,
      icon_note_time: Images.icon_note_time_dark,
      icon_info: Images.icon_info_dark,
      icon_select: Images.icon_select_dark,
      icon_profile: Images.icon_profile_dark,
      icon_del_back: Images.icon_del_back_light,
      icon_forward: Images.icon_forward_dark,
      // location_header_Icon: Images.earth_dark,
      // icon_back: Images.icon_back_dark,
      // icon_logo: Images.LogoWhite,
      // refBanner: Images.RefMainImg,
      icon_buy_sell: Images.icon_buy_sell_dark,
      icon_checked: Images.icon_checked,
      //icon new
      icon_home_active: Images.iconHomeActiveDark,
      icon_home_inactive: Images.iconHomeInactiveDark,
      icon_market_active: Images.iconMarketActiveDark,
      icon_market_inactive: Images.iconMarketInactiveDark,
      icon_trade_active: Images.iconTradesActiveDark,
      icon_trade_inactive: Images.iconTradeInActiveDark,
      icon_wallet_active: Images.iconWalletActiveDark,
      icon_wallet_inactive: Images.iconWalletInactiveDark,
      icon_card_active: Images.iconCardActiveDark,
      icon_card_inactive: Images.inactiveCardsDark,
      icon_profile_k: Images.icon_profile_dark_k,
      icon_notification_k: Images.icon_notification_dark_k,

      icon_deposit: Images.iconDepositDark,
      icon_withdraw: Images.iconWithdrawDark,
      icon_spot: Images.iconSpotDark,
      icon_swap_k: Images.iconSwapDark,
      icon_earth: Images.icon_earth_dark,
      icon_open_eye: Images.icon_open_eye_dark,
      icon_select_k: Images.icon_select_dark_k,
      icon_cross: Images.cross_dark,
      icon_spot_right: Images.icon_spot_right_dark,
      noOpenOrder: Images.noOpenOrderDark,
      icon_add: Images.icon_add_dark,
      icon_back: Images.icon_back_dark,
      mode: Images.mode_dark,
      icon_forward_arrow: Images.icon_forward_arrow_dark,
      icon_Profile_Settings: Images.icon_Profile_Settings_dark,
      icon_Profile_Kyc: Images.icon_Profile_Kyc_dark,
      icon_profile_Share: Images.icon_profile_Share_dark,
      Icon_Profile_Copy: Images.Icon_Profile_Copy_dark,
      icon_facebook: Images.icon_facebook_dark,
      icon_telegram: Images.icon_telegram_dark,
      icon_twitter: Images.icon_twitter_dark,
      icon_update: Images.icon_update_dark,
      icon_phone: Images.icon_phone_dark,
      Logo_MAIN: Images.Logo_MAIN_dark,
      iconCardsInactive: Images.inactiveCardsDark,
      iconCardActive: Images.iconCardActiveDark,
      icon_User_CreateAccount: Images.icon_User_CreateAccount_dark,
      icon_indentity_CreateAccount: Images.icon_indentity_CreateAccount_dark,
      iconDeleteUser: Images.iconDeleteUserDark,
      icon_ph: Images.icon_ph_dark,
      icon_caution: Images.icon_caution_dark,
      icon_down: Images.icon_down_dark,
      icon_up: Images.icon_up_dark,
      freeze_card: Images.freeze_card_dark,
      view_pin: Images.view_pin_dark,
      icon_upload_doc: Images.icon_upload_doc_dark,
      icon_edit: Images.icon_edit_dark,
      icon_replace_card: Images.icon_replace_card_dark,
      qr_scanner: Images.qr_scanner_dark,


      // icon_search_text: Images.search_text_icon, //icon_search_text_dark,
      icon_search_text: Images.icon_search_text_dark,

      // icon_swap_c: Images.swap_location,//Images.icon_swap_dark_k,
      icon_swap_c: Images.icon_swap_dark_k,

      // icon_hide_eye: Images.hidePassword,//icon_hide_eye_dark,
      icon_hide_eye: Images.icon_hide_eye_dark,

      // icon_close_main: Images.closeLogin,// Images.icon_close_dark,
      icon_close_main: Images.icon_close_dark,

      bgImage: Images.darkBG,
      earth_icon: Images.icon_earth_dark,//earth_icon,

    },
  },
});
