import { StyleSheet } from "react-native";
import fonts from "../../../theme/fonts";
import { colors, Fonts } from "../../../theme";
import { ThemeManager } from "../../../../ThemeManager";

const useStyles = (theme) =>
  StyleSheet.create({
    viewPasswordImage: {
      height: 16,
      width: 16,
      resizeMode: "center",
    },
    userInfoView: {
      flexDirection: "row",
      alignContent: "center",
      marginVertical: 20,
      justifyContent: "space-between",
      paddingLeft: 16,
    },
    rowFlex: { flexDirection: "row" },
    emailPhonetext: {
      fontSize: 18,
      fontFamily: fonts.regular,
    },
    viewEmailPhone: {
      left: 4,
      alignSelf: "center",
      top: 6,
    },
    IdText: {
      fontSize: 14,
      fontFamily: fonts.regular,
    },
    verifiedView: {
      flexDirection: "row",
      backgroundColor: colors.buttonBgColor,
      alignContent: "center",
      alignItems: "center",
      padding: 6,
      borderBottomLeftRadius: 15,
      borderTopLeftRadius: 15,
      height: 30,
    },
    verifiedImage: { marginLeft: 10, marginRight: 6, height: 18, width: 15 },
    verifiedText: {
      fontSize: 14,
      fontFamily: fonts.regular,
      color: colors.white,
    },
    infoView: {
      marginHorizontal: 16,
      marginVertical: 15,
      height: 60,
      backgroundColor: colors.white,
      alignItems: "center",
      paddingLeft: 15,
      flexDirection: "row",
    },
    customRightImage: {
      width: 12,
      height: 12,
      right: 32,
      tintColor: theme.colors.textColor,
      resizeMode: "contain",
    },
    modeIcon: {
      width: 23,
      height: 23,
      right: 32,
      tintColor: theme.colors.textColor,
      resizeMode: "contain",
    },
    backgroundView: {
      backgroundColor: theme.colors.dashboardSubViewBg,
    },
    warningText: {
      alignSelf: "center",
      marginHorizontal: 16,
      color: colors.dashboarItemLightText,
      fontFamily: fonts.regular,
      fontSize: 12,
      marginBottom: 20,
    },
    onceText: {
      color: theme.colors.inactiveTextColor,
      fontSize: 14,
      fontFamily: Fonts.regular,
      marginLeft: 42,
      marginRight: 20,
      marginBottom: 30,
    },
    youRequested: {
      marginHorizontal: 8,
      color: theme.colors.textColor,
      fontFamily: fonts.regular,
      fontSize: 12,
    },
    profileIconStyle: { height: 20, width: 20, resizeMode: "contain" },
    headerView: { marginHorizontal: 20, height: 45 },
    notificationBtn: {
      justifyContent: "space-between",
      flexDirection: "row",
      alignItems: "center",
      marginHorizontal: 15,
      marginVertical: 15,
    },
    notificationView: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-start",
    },
    notificationBtnIcon: {
      width: 20,
      height: 20,
      resizeMode: "contain",
    },
    notificationBtnText: {
      color: theme.colors.headTxt,
      fontSize: 16,
      fontFamily: fonts.regular,
      marginLeft: 10,
    },
    unreadView: {
      height: 10,
      width: 10,
      borderRadius: 5,
      backgroundColor: theme.colors.selectedTextColor,
      marginRight: 10,
    },
    unreadArrow: { height: 12, width: 12, resizeMode: "contain" },
    mainContainer: {
      flex: 1,
      backgroundColor: theme.colors.DashboardBG,
      justifyContent: "space-between",
    },
    subContainer: { justifyContent: "space-between", flex: 1 },
    headerDeleteText: {
      fontSize: 24,
      fontFamily: Fonts.medium,
      color: theme.colors.textColor,
      marginTop: 10,
      marginHorizontal: 15,
    },
    infoView: {
      marginHorizontal: 16,
      paddingHorizontal: 10,
      marginVertical: 15,
      height: 60,
      backgroundColor: theme.colors.tabBackground,
      // backgroundColor: colors.white,
      alignItems: "center",
      paddingLeft: 15,
      flexDirection: "row",
      flex: 1,
      borderRadius: 6,
      // flexShrink: 0,
    },
    customRightImage: {
      width: 12,
      height: 12,
      right: 32,
      // tintColor: theme.colors.inactiveTextColor,
      resizeMode: "contain",
    },
    modeIcon: {
      width: 23,
      height: 23,
      right: 32,
      tintColor: theme.colors.textColor,
      resizeMode: "contain",
    },
    btnBottom: {
      marginBottom: 30,
      marginLeft: 15,
      marginRight: 15,
      // backgroundColor: ThemeManager.colors.selectedTextColor,
      backgroundColor: theme.colors.walletDPbtn,
    },
    textModalStyle: {
      fontSize: 16,
      fontFamily: Fonts.medium,
      color: theme.colors.textColor,
      // marginTop: 5,
      marginLeft: 15,
    },
    accessText: {
      fontSize: 16,
      fontFamily: Fonts.medium,
      color: theme.colors.textColor,
      marginTop: 10,
      marginLeft: 15,
    },
    looseText: {
      fontSize: 16,
      fontFamily: Fonts.medium,
      color: theme.colors.textColor,
      textDecorationLine: "underline",
      marginTop: 10,
      marginLeft: 15,
    },
    enterText: {
      fontSize: 18,
      fontFamily: Fonts.medium,
      color: theme.colors.textColor,
      marginTop: 10,
      marginLeft: 15,
    },
    accountDeleteText: {
      fontSize: 14,
      fontFamily: Fonts.regular,
      color: theme.colors.textRedColor,
      marginTop: 10,
      marginHorizontal: 15,
    },
    totalBalanceText: {
      fontSize: 14,
      fontFamily: Fonts.regular,
      color: theme.colors.textColor,
      marginVertical: 10,
      marginHorizontal: 15,
    },
    beforeDeleteText: {
      fontSize: 14,
      fontFamily: Fonts.regular,
      color: theme.colors.textColor,
      marginTop: 10,
      marginHorizontal: 15,
    },
    viewModal: {
      backgroundColor: "rgba(255,255,255,0.1)",
      margin: 20,
      padding: 10,
    },
    errorMessageStyle: {
      fontSize: 15,
      color: "red",
      alignSelf: "center",
    },
  });
export default useStyles;
